# Generated by Django 5.1.7 on 2025-03-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_id", models.IntegerField(unique=True)),
                ("school", models.CharField(max_length=100)),
                ("abbr", models.CharField(max_length=10)),
                ("conference", models.CharField(max_length=100)),
                ("division", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
