# Generated by Django 5.1.7 on 2025-03-21 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CFBDash", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conference", models.CharField(max_length=100)),
                ("stat", models.CharField(max_length=100)),
                ("stat_value", models.IntegerField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        related_query_name="stat",
                        to="CFBDash.team",
                    ),
                ),
            ],
        ),
    ]
