# Generated by Django 5.1.7 on 2025-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CFBDash", "0002_teamstat"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
